name: Compress Unity
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Compress Folder
        run: zip -r -q folder.zip folder

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: '["folder.zip"]'
          message: 'Automated commit: Updated zip file'
          push: true
